version: '3.8'

services:
  db:
    image: postgres:14.4
    restart: always
    container_name: thinkOn-database
    environment:
      - POSTGRES_PASSWORD=1195
      - POSTGRES_USER=postgres
      - POSTGRES_DB=thinkOn_users_db
    ports:
      - "5432:5432"
  backend:
    build: .
    container_name: thinkOn-app
    ports:
      - "28852:28852"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/thinkOn_users_db
